import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const supervisor = readFileSync('apps/web/app/lib/runtime-supervisor.ts', 'utf8');
const runtime = readFileSync('apps/web/app/lib/minion-runtime.ts', 'utf8');
const route = readFileSync('apps/web/app/minions/[minionId]/page.tsx', 'utf8');
const runtimeStore = readFileSync('apps/web/app/lib/runtime-store.ts', 'utf8');
const credentialStore = readFileSync('apps/web/app/lib/credential-store.ts', 'utf8');
const credentialsRoute = readFileSync('apps/web/app/api/credentials/route.ts', 'utf8');
const credentialPanel = readFileSync('apps/web/app/dashboard/credential-setup-panel.tsx', 'utf8');

assert.match(supervisor, /from 'node:child_process'/, 'supervisor must use Node child_process');
assert.match(supervisor, /spawn\(/, 'launch must spawn a real process');
assert.match(supervisor, /shell:\s*false/, 'launch must not use a shell command string');
assert.match(supervisor, /MINIONMINT_SELF_HOSTED_EXECUTABLE/, 'launch executable must be configured structurally');
assert.match(supervisor, /MINIONMINT_SELF_HOSTED_ARGS_JSON/, 'launch args must be configured as JSON argv');
assert.match(supervisor, /\{profile\}|\{config\}|\{workspace\}|\{minionId\}/, 'launch must support only explicit placeholders');
assert.match(supervisor, /process\.kill\(pid, 0\)/, 'status must check the actual stored PID');
assert.match(supervisor, /process\.kill\(state\.pid, 'SIGTERM'\)/, 'stop must signal the actual stored PID');
assert.match(runtime, /runtime\.log/, 'runtime must assign a per-Minion runtime log path');
assert.match(supervisor, /recentLogLines/, 'supervisor must return recent log evidence');

assert.match(runtime, /launchSelfHostedRuntime\(/, 'launch_minion must call the supervisor');
assert.match(runtime, /checkSelfHostedRuntimeStatus\(/, 'status_check must call the supervisor');
assert.match(runtime, /stopSelfHostedRuntime\(/, 'stop_minion must call the supervisor');
assert.doesNotMatch(runtime, /workspaceStatus = 'running';\n\s*next\.processSupervisor = processSupervisor\('running'/, 'launch_minion must not be only a status flip');
assert.match(runtime, /workspaceUrlFor\(minionId\)/, 'Open Minion must use an app console route, not file URLs');
assert.doesNotMatch(runtime, /file:\/\//, 'runtime open URL must not be only a file URL');
assert.match(runtime, /Scaffolded credential refs are not encrypted/, 'scaffolded credential refs must not be treated as secure');
assert.match(runtime, /MINIONMINT_ALLOW_SCAFFOLDED_CREDENTIAL_REFS_FOR_DEV/, 'dev-only scaffolded credential launch must be explicit');
assert.match(runtime, /runtimePathSignature/, 'runtime must compute a path signature for stale-state detection');
assert.match(runtime, /supervisorStateMatchesRuntimePaths/, 'runtime must compare stored supervisor paths with current runtime paths');
assert.match(runtime, /resetSupervisorForPathChange/, 'runtime must reset stale supervisor state after path changes');
assert.match(runtime, /Runtime workspace path changed; supervisor state reset for safety\./, 'runtime must log path-change reset');
assert.match(runtime, /pid:\s*null/, 'path reset must clear old PID');
assert.match(runtime, /recentLogLines:\s*\[\]/, 'path reset must clear old recent log lines');
assert.match(runtime, /startedAt:\s*null/, 'path reset must clear old startedAt');
assert.match(runtime, /stoppedAt:\s*null/, 'path reset must clear old stoppedAt');
assert.match(runtime, /sanitizeSupervisorForCurrentPaths\(next\)/, 'actions must sanitize stale supervisor state before status, stop, or launch');
assert.match(runtime, /readRuntimeStoreForUser/, 'runtime transitions must read through runtime store abstraction');
assert.match(runtime, /upsertRuntimeForUser/, 'runtime preparation must upsert through runtime store abstraction');
assert.match(runtime, /updateRuntimeForUser/, 'runtime actions must persist through runtime store abstraction');
assert.doesNotMatch(runtime, /minion-runtimes\.json/, 'minion-runtime should not directly own local fallback persistence');

assert.match(runtimeStore, /PrismaClient/, 'runtime store must support Prisma Client');
assert.match(runtimeStore, /DATABASE_URL/, 'runtime store must switch to Prisma when DATABASE_URL is configured');
assert.match(runtimeStore, /MINIONMINT_FORCE_LOCAL_STORE/, 'runtime store must preserve forced local fallback');
assert.match(runtimeStore, /client\.minionRuntime\.upsert/, 'runtime store must upsert MinionRuntime rows');
assert.match(runtimeStore, /client\.minionRuntime\.update/, 'runtime store must update MinionRuntime rows after actions');
assert.match(runtimeStore, /client\.minionRuntime\.findFirst/, 'runtime store must read MinionRuntime rows through tenant-scoped filters');
assert.match(runtimeStore, /clerkUserId/, 'runtime store must resolve signed-in users by clerkUserId');
assert.match(runtimeStore, /memberships/, 'runtime store must restrict reads to owner org memberships');
assert.match(runtimeStore, /local_fallback/, 'runtime store must retain local fallback mode');

assert.match(credentialStore, /CredentialSetupRecord/, 'credential setup must have a durable owner state model');
assert.match(credentialStore, /credential-setups\.json/, 'credential setup must preserve local fallback records');
assert.match(credentialStore, /credentialSetup\.findMany/, 'credential setup must read Prisma rows when DATABASE_URL is configured');
assert.match(credentialStore, /credentialSetup\.create/, 'credential setup must persist Prisma rows when DATABASE_URL is configured');
assert.match(credentialStore, /credentialType: CredentialType/, 'credential setup must record provider-neutral credential type');
assert.match(credentialStore, /allowedUse/, 'credential setup must record owner allowed-use notes');
assert.match(credentialStore, /redactedValue/, 'credential setup must expose only redacted values');
assert.match(credentialStore, /secretCiphertext/, 'credential setup may store encrypted local vault material when a key is configured');
assert.match(credentialStore, /vaultRefFor/, 'credential setup must mint vault://local or vault://postgres refs instead of reusing submitted values');
assert.match(credentialStore, /vault:\/\/local\//, 'local fallback credentials must use local vault refs');
assert.match(credentialStore, /vault:\/\/postgres\//, 'Postgres credentials must use Postgres vault refs');
assert.match(credentialStore, /isCredentialSetupLaunchReady/, 'credential setup must expose launch readiness gate');
assert.match(credentialStore, /setup\.encrypted === true/, 'launch readiness must require encrypted credential setup state');
assert.match(credentialStore, /credentialReadinessFor\(refs[\s\S]*encrypted = false/, 'credential readiness must accept encrypted state explicitly');
assert.match(credentialStore, /refsUseExternalEncryptedManager/, 'external encrypted manager refs must be classified separately from generated local refs');
assert.match(credentialStore, /submittedExternalRef \? \[normalizedValue\]/, 'external encrypted manager refs should be stored as references without wrapping raw local values');
assert.match(runtime, /credentialVaultMetadataFor/, 'runtime must write credential vault metadata from credential setup state');
assert.match(runtime, /const encrypted = Boolean\(setup\?\.encrypted\)/, 'credential refs file must report encrypted metadata accurately');
assert.match(runtime, /const readiness = setup\?\.readiness/, 'credential refs file must report credential setup readiness accurately');
assert.match(runtime, /Scaffolded or unencrypted credential refs are not encrypted credentials/, 'credential refs warning must remain for pending, scaffolded, or unencrypted refs');
assert.match(runtime, /writeSelfHostedRuntimeFiles\(next, credentialSetup\)/, 'runtime file generation must receive the ready credential setup before launch');
assert.match(runtime, /Generated real per-Minion Hermes profile and encrypted credential vault refs metadata/, 'runtime logs must distinguish encrypted credential refs metadata from scaffold refs');
assert.match(runtime, /owner credential setup readiness/, 'launch block log must name owner credential setup readiness');
assert.match(credentialsRoute, /returns redacted values only/, 'API must describe safe redacted responses');
assert.match(credentialsRoute, /if \(!credentialValue\.trim\(\)\)/, 'credentials API must reject missing credential value before persistence');
assert.match(credentialsRoute, /try \{[\s\S]*saveCredentialSetupForUser/, 'credentials API must wrap expected store errors safely');
assert.match(credentialsRoute, /isAuthorizationError \? 403 : isValidationError \? 400 : 500/, 'credentials API must map expected validation and authorization errors to safe HTTP statuses');
assert.doesNotMatch(credentialsRoute, /stack/, 'credentials API must not echo stack traces in errors');
assert.match(credentialPanel, /Reference or secret value/, 'dashboard must let the owner add references or local values');
assert.match(credentialPanel, /Credential type/, 'dashboard must include generic credential type selection');
assert.match(credentialPanel, /Allowed use notes/, 'dashboard must include owner allowed-use notes');
assert.match(credentialPanel, /redacted values only/, 'dashboard must warn that saved credential values are redacted');
assert.doesNotMatch(credentialPanel, /secretValue|passwordValue|apiKeyValue|tokenValue/, 'dashboard credential setup must not expose raw credential value fields');

assert.match(route, /Minion console/);
assert.match(route, /Owner takeover/);
assert.match(route, /Recent runtime logs/);
assert.match(route, /getRuntimeByMinionId/);

console.log('runtime supervisor launch, PID status, stop, logs, console route, and credential guardrails are present.');
